spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/gulimall_pms
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml #mybatis映射文件位置
  global-config:
    db-config:
      id-type: auto #mybatis全局主键自增
      logic-delete-value: 1
      logic-not-delete-value: 0
