server:
  port: 5000
spring:
  application:
    name: gulimall-product
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://114.115.138.227:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 114.115.138.227:8848

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml #mybatis映射文件位置
  global-config:
    db-config:
      id-type: auto #mybatis全局主键自增
      logic-delete-value: 1
      logic-not-delete-value: 0