spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://114.115.138.227:3306/gulimall_oms
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml #mybatis映射文件位置
  global-config:
    db-config:
      id-type: auto #mybatis全局主键自增
      logic-delete-value: 1
      logic-not-delete-value: 0
